spring:
  datasource:
    username: jongwoo
    password: pass
    url: jdbc:postgresql://localhost:5432/jpashop
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
server:
  port: 8081